name: civic_link
description: "A Civic Issue Reporting App"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Firebase packages
  firebase_core: ^2.32.0
  firebase_auth: ^4.20.0
  cloud_firestore: ^4.17.5
  firebase_storage: ^11.7.7
  firebase_messaging: ^14.7.10

  # Other packages
  animated_text_kit: ^4.2.2
  geolocator: ^11.1.0
  image_picker: ^1.0.4
  google_fonts: ^4.0.5
  flutter_vector_icons: ^2.0.0
  provider: ^6.1.2
  pin_code_fields: ^8.0.1
  shimmer: ^2.0.0
  google_maps_flutter: ^2.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/logo.png
    - assets/city_background.jpg